# Generated by Django 5.2 on 2025-04-25 00:39

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('referencia', models.CharField(blank=True, max_length=50, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('costo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('precio', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Transportadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_actual', models.IntegerField(default=0)),
                ('umbral_minimo', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('sin_stock', 'Sin stock'), ('stock_bajo', 'Stock bajo'), ('en_stock', 'En stock')], default='en_stock', max_length=20)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envios.bodega')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envios.producto')),
            ],
        ),
        migrations.CreateModel(
            name='GuiaEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_guia', models.CharField(max_length=20, unique=True)),
                ('cliente_nombre', models.CharField(max_length=100)),
                ('cliente_telefono', models.CharField(max_length=20)),
                ('cliente_ciudad', models.CharField(max_length=50)),
                ('cliente_direccion', models.TextField()),
                ('contenido', models.CharField(max_length=100)),
                ('cantidad', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('en_transito', 'En tránsito'), ('entregada', 'Entregada')], default='activa', max_length=20)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('transportadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='envios.transportadora')),
            ],
        ),
    ]
