# Generated by Django 5.2 on 2025-04-25 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GuiaEnvio',
        ),
        migrations.DeleteModel(
            name='Transportadora',
        ),
    ]
