# Generated by Django 5.2 on 2025-04-25 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0002_delete_guiaenvio_delete_transportadora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bodega',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='bodega',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bodega',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
