# Generated by Django 5.2 on 2025-04-26 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0003_remove_bodega_ubicacion_bodega_direccion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuiaEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nombre', models.CharField(max_length=100)),
                ('cliente_telefono', models.CharField(max_length=20)),
                ('cliente_ciudad', models.CharField(max_length=50)),
                ('cliente_direccion', models.TextField()),
                ('cliente_direccion2', models.TextField(blank=True, null=True)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('contenido', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('preparacion', 'En preparación'), ('transito', 'En tránsito'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('codigo_seguimiento', models.CharField(blank=True, max_length=20, unique=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guias', to='envios.producto')),
            ],
            options={
                'verbose_name': 'Guía de Envío',
                'verbose_name_plural': 'Guías de Envío',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
