# Generated by Django 5.2 on 2025-05-28 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0004_guiaenvio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guiaenvio',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='guiaenvio',
            name='contenido',
        ),
        migrations.RemoveField(
            model_name='guiaenvio',
            name='producto',
        ),
        migrations.AddField(
            model_name='guiaenvio',
            name='contenido_resumen',
            field=models.CharField(blank=True, help_text='Resumen textual de los productos.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='guiaenvio',
            name='cliente_ciudad',
            field=models.CharField(choices=[('Guayaquil', 'Guayaquil'), ('Quito', 'Quito')], max_length=50, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='guiaenvio',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha y hora de modificación'),
        ),
        migrations.AlterField(
            model_name='guiaenvio',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora de creación'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='estado',
            field=models.CharField(choices=[('ok', 'Stock OK'), ('bajo', 'Stock Bajo'), ('sin', 'Sin Stock')], default='ok', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_actual',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stock',
            name='umbral_minimo',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='GuiaEnvioProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario_en_guia', models.DecimalField(decimal_places=2, help_text='Precio del producto al momento de crear la guía', max_digits=10)),
                ('guia_envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_guia', to='envios.guiaenvio')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='envios.producto')),
            ],
            options={
                'verbose_name': 'Producto en Guía de Envío',
                'verbose_name_plural': 'Productos en Guías de Envío',
                'unique_together': {('guia_envio', 'producto')},
            },
        ),
    ]
