# Generated by Django 5.2 on 2025-05-28 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0005_remove_guiaenvio_cantidad_remove_guiaenvio_contenido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guiaenvio',
            name='cantidad',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Cantidad Principal (Opcional)'),
        ),
        migrations.AddField(
            model_name='guiaenvio',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guias_como_principal', to='envios.producto', verbose_name='Producto Principal (Opcional)'),
        ),
        migrations.AlterField(
            model_name='guiaenvio',
            name='contenido_resumen',
            field=models.CharField(blank=True, help_text='Resumen textual de los productos de la tabla.', max_length=500, null=True),
        ),
    ]
