# Generated by Django 5.2 on 2025-05-28 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0006_guiaenvio_cantidad_guiaenvio_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guiaenvio',
            name='cantidad',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Cantidad Principal (Automático/Opcional)'),
        ),
        migrations.AlterField(
            model_name='guiaenvio',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guias_como_principal', to='envios.producto', verbose_name='Producto Principal (Automático/Opcional)'),
        ),
    ]
