# Generated by Django 5.2 on 2025-05-28 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0007_alter_guiaenvio_cantidad_alter_guiaenvio_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gui_string', models.CharField(max_length=255, unique=True)),
                ('pais', models.CharField(max_length=3)),
                ('plataforma', models.CharField(max_length=1)),
                ('tipo_campana', models.CharField(max_length=10)),
                ('fecha', models.DateField()),
                ('nombre_reloj', models.CharField(max_length=100)),
                ('id_reloj', models.CharField(max_length=20)),
                ('persona', models.CharField(max_length=2)),
                ('num_importacion', models.CharField(max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Campaña',
                'verbose_name_plural': 'Campañas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='guiaenvio',
            name='cantidad',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Cantidad Principal (Automático)'),
        ),
        migrations.AlterField(
            model_name='guiaenvio',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guias_como_principal', to='envios.producto', verbose_name='Producto Principal (Automático)'),
        ),
    ]
