# Generated by Django 5.2 on 2025-06-01 21:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0008_campaign_alter_guiaenvio_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodega',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='id_reloj',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='num_importacion',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='persona',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='plataforma',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='guiaenvio',
            name='cantidad',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Cantidad Principal (Ref.)'),
        ),
        migrations.AlterField(
            model_name='guiaenvio',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guias_como_principal', to='envios.producto', verbose_name='Producto Principal (Ref.)'),
        ),
    ]
